[package]
name = "petgraph-cypher"
version = "0.1.0"
edition = "2024"
authors = ["Markus Mayer <widemeadows@gmail.com>"]
description = "Build petgraph graphs from OpenCypher queries"
license = "EUPL-1.2 OR MIT OR Apache-2.0"
repository = "https://github.com/sunsided/petgraph-cypher"
readme = "README.md"
keywords = ["petgraph", "cypher", "opencypher", "graph"]
categories = ["data-structures"]

[dependencies]
petgraph = "0.8"
nom = "7"
thiserror = "2"
itertools = "0.13"
